//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatting_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Chatting_AppEntities : DbContext
    {
        public Chatting_AppEntities()
            : base("name=Chatting_AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbContact> tbContacts { get; set; }
        public virtual DbSet<tbMessage> tbMessages { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
