//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatting_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContact
    {
        public string UserContactNumber { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    
        public virtual tbUser tbUser { get; set; }
        public virtual tbUser tbUser1 { get; set; }
    }
}
