USE [master]
GO

/****** Object:  Database [IMS]    Script Date: 4/30/2025 2:40:33 AM ******/
CREATE DATABASE [IMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IMS_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [IMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IMS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [IMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IMS] SET RECOVERY FULL 
GO

ALTER DATABASE [IMS] SET  MULTI_USER 
GO

ALTER DATABASE [IMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [IMS] SET QUERY_STORE = ON
GO

ALTER DATABASE [IMS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [IMS] SET  READ_WRITE 
GO


